version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - SORRORITY_PORT=5000
      - SORRORITY_ADMIN_PORT=5001
      - SORRORITY_CONFIG=/usr/src/app/config.yml
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=sorrority
      - POSTGRES_USER=shabbat
      - POSTGRES_PASSWORD=yomkippur
    volumes:
      - ./config.example.yml:/usr/src/app/config.yml
    depends_on:
      - db

  db:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SORRORITY_DB=sorrority
      - SORRORITY_USER=shabbat
      - SORRORITY_PASSWORD=yomkippur
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
